### ISSUE TITLE
#include "png.h" bug

### ISSUE THREAD

**Issue by gumernus** [thaddeus002/yImage#1]
for some reason I have this error when I run "make"

![image](https://user-images.githubusercontent.com/70224036/169876391-fc48223b-6c9f-498c-97d8-6991446da25a.png)

**Comment by gumernus** [comment]
I think i need `libz and libpng-1.6 for png reading and writing` or something

**Comment by thaddeus002** [comment]
If you don't need PNG support, try building with : `HAVE_PNG=no make`.
Otherwise, you will have to install `libpng` and edit the `Makefile` to set the constant `INCLUDEPNG` with the correct path.

**Comment by thaddeus002** [comment]
Build instructions have been added in the _README_ file. I think I won't do more since I don't want to remove PNG support for the default build.
I will close this issue in a few weeks if there is no new comment before.

**Comment by gumernus** [comment]
Yea i guess its okay. I started using [PngWriter](https://github.com/feham/PngWriter/pull/4) instead.
